// AUTO-GENERATED by scripts/gen-image-dimensions.mjs - do not edit by hand.
// Maps each bundled image URL to its intrinsic [width, height] so <img> tags can
// reserve the right space before the file loads.

import a0 from '../../imports/1781900331401__2_.webp';
import a1 from '../../imports/dsgn386/p01_0.webp';
import a2 from '../../imports/dsgn386/p04_0.webp';
import a3 from '../../imports/dsgn386/p04_1.webp';
import a4 from '../../imports/dsgn386/p04_2.webp';
import a5 from '../../imports/dsgn386/p05_0.webp';
import a6 from '../../imports/dsgn386/p06_0.webp';
import a7 from '../../imports/dsgn386/p06_1.webp';
import a8 from '../../imports/dsgn386/p06_2.webp';
import a9 from '../../imports/dsgn386/p07_0.webp';
import a10 from '../../imports/dsgn386/p07_1.webp';
import a11 from '../../imports/dsgn386/p08_0.webp';
import a12 from '../../imports/dsgn386/p08_1.webp';
import a13 from '../../imports/dsgn386/p09_0.webp';
import a14 from '../../imports/dsgn386/p10_0.webp';
import a15 from '../../imports/dsgn386/p10_1.webp';
import a16 from '../../imports/dsgn386/p12_0.webp';
import a17 from '../../imports/dsgn386/p13_0.webp';
import a18 from '../../imports/dsgn386/p13_1.webp';
import a19 from '../../imports/dsgn386/p16_0.webp';
import a20 from '../../imports/dsgn386/p21_0.webp';
import a21 from '../../imports/dsgn386/p27_0.webp';
import a22 from '../../imports/dsgn386/p27_1.webp';
import a23 from '../../imports/dsgn386/p28_0.webp';
import a24 from '../../imports/dsgn386/p28_1.webp';
import a25 from '../../imports/dsgn386/p29_0.webp';
import a26 from '../../imports/dsgn386/p29_1.webp';
import a27 from '../../imports/waterguard/wg-front-dome.webp';
import a28 from '../../imports/waterguard/wg-front-panel.webp';
import a29 from '../../imports/waterguard/wg-installed-front.webp';
import a30 from '../../imports/waterguard/wg-installed-rear.webp';
import a31 from '../../imports/waterguard/wg-runoff-rear.webp';
import a32 from '../../imports/waterguard/wg-runoff-sketch.webp';
import a33 from '../../imports/waterguard/wg-slope-test.webp';
import a34 from '../../imports/waterguard/wg-weld-leak-test.webp';
import a35 from 'figma:asset/03ed3a93bcfbfaca1b365a293a02bbbc999da73f.webp';
import a36 from 'figma:asset/04364e8a8e32e2ac680bc5eceae50dae3c413998.webp';
import a37 from 'figma:asset/05940af68dd4baf865ad8f3c9cf984dd2f00c23d.webp';
import a38 from 'figma:asset/05b77ea1a86341595dc1893c29562b5cdf00ccdf.webp';
import a39 from 'figma:asset/0618a99fac31a4b599e1bd742d40be07567a8984.webp';
import a40 from 'figma:asset/0b7d6aceecd4965ee53ded4f68832dab8a0d08a0.webp';
import a41 from 'figma:asset/0c930a2a913495aa9b1d94e33057b7d9868884a5.webp';
import a42 from 'figma:asset/0da3efe4925c16eb36e4ebf526f92081949c8190.webp';
import a43 from 'figma:asset/134ccdf2ef97521532df170a438af63ee9c27808.webp';
import a44 from 'figma:asset/1a30b5256c61ddd0c124b6e7f825c1934e09de8d.webp';
import a45 from 'figma:asset/1d18a7808e8709de495f1254f14773c637ad686b.webp';
import a46 from 'figma:asset/29f7fee3d4abf8c0036a9ec2ed22cb709df1d475.webp';
import a47 from 'figma:asset/2db359936a3d16f421f5cdfeb24d599ebbb304bb.webp';
import a48 from 'figma:asset/32f02bacb93f261ec836820c9e1bafe4367f7e6b.webp';
import a49 from 'figma:asset/341fc91b3513084249553e6967f56281fd6c8645.webp';
import a50 from 'figma:asset/393d470593ff653ebfaa60468f1a33d6fdc77742.webp';
import a51 from 'figma:asset/3b5611915cfa8c0522559efe6b31ea2a9eb1adc0.webp';
import a52 from 'figma:asset/3d1001aaaadf39cac5581426cd1b1ce32f967ffa.webp';
import a53 from 'figma:asset/3d94ecf2fb9bc0ccd594db6d4135fcb6c4c64658.webp';
import a54 from 'figma:asset/4912cd11da20c60b00c965ea83b87634b57600b8.webp';
import a55 from 'figma:asset/4beb1f92bb835754bb2566c92a7370ee22877fbb.webp';
import a56 from 'figma:asset/5b1ae5f356afbd5aba632c5c944a1bb8a776bbee.webp';
import a57 from 'figma:asset/5ca57543960765bbe4baf8c8a0d5ac7b885bd760.webp';
import a58 from 'figma:asset/5cee417e0193e39fee7a6810170438020872701d.webp';
import a59 from 'figma:asset/5e0b5e24d0664f57617d6cecfa722e59f6a3cc65.webp';
import a60 from 'figma:asset/61495f2f3972a37806c764376ced254c1023b957.webp';
import a61 from 'figma:asset/633353b4b72dc0dbc1d456088ec370adeeb2d911.webp';
import a62 from 'figma:asset/67df7d20c56a35cc1886b1a1ac222d25f068f33f.webp';
import a63 from 'figma:asset/68a526a5c922e5ab9f4266241352abe1973792f8.webp';
import a64 from 'figma:asset/6ed8612593887b9aed22bafeb70c6a707ef7b9e3.webp';
import a65 from 'figma:asset/6f4325245aa689e63a3b4eb0653b90c207882c29.webp';
import a66 from 'figma:asset/72fc3068db2c54d65007e0d0de4e75aa2d7810bc.webp';
import a67 from 'figma:asset/7427c8a0ec2a5ca6b54ffd3391bdc25cef6a5940.webp';
import a68 from 'figma:asset/74d139f8b070cd88eca71f5874788d4232ca87cf.webp';
import a69 from 'figma:asset/75bb6d7fa5b40b10fe624772fa2650c2d6f33de0.webp';
import a70 from 'figma:asset/796b3fa8b16982c6bbf592edfa22d051d63b3e2d.webp';
import a71 from 'figma:asset/7b7a8d330415d2d8c94cdec9942f41b950aefcf0.webp';
import a72 from 'figma:asset/7d7800d37d6621032f1d80a4f4b579540d7cac5e.webp';
import a73 from 'figma:asset/8245392aa6ee2b4d710b552de641679ad8f4bc12.webp';
import a74 from 'figma:asset/842b7f02835e24e02409becfc9b36ec43e4de781.webp';
import a75 from 'figma:asset/855c7fe4fa1b4b10045986c1830e5a624914d6fb.webp';
import a76 from 'figma:asset/89f206ac09798ea1c47f84428c7ec369962f1e78.webp';
import a77 from 'figma:asset/8e0e8033d043030122e4156d932b40a343273916.webp';
import a78 from 'figma:asset/8f6f3a36e6bb445ed579fe22534757d7379817a8.webp';
import a79 from 'figma:asset/90db89c8c1d7788fc96270ad95185295051741c8.webp';
import a80 from 'figma:asset/95c90a41bda86117a9907b3b13affa564ef736e5.webp';
import a81 from 'figma:asset/96d3b7ea91351b38a4e051cdb802ac4915721f4e.webp';
import a82 from 'figma:asset/9794f6b646dbc637e8893cf2fc7a0e216b75a36a.webp';
import a83 from 'figma:asset/9ca8735e78ca466a53244803b9120e281979b4cc.webp';
import a84 from 'figma:asset/9cd3729e78f71bd38f4585d1bab1cfd08586e862.webp';
import a85 from 'figma:asset/9cfe9259f08f7d6d1896d5f78dec9f9932c1befa.webp';
import a86 from 'figma:asset/9ef7d8d4e2fe940d318007df98509c59079bb4ca.webp';
import a87 from 'figma:asset/a16c216657da11ee1f80bf06965f4bb55df125c6.webp';
import a88 from 'figma:asset/ac51133386d81e89aead318892b53b5efc52cdd1.webp';
import a89 from 'figma:asset/afe93b8fb36b3a1f176026cfb5f3067d51dfe582.webp';
import a90 from 'figma:asset/b0b82af46ce1e6db6a9a0a3fccd9728443f1195e.webp';
import a91 from 'figma:asset/b209b20130571e3a9a1d40c13b20aabd60753d7d.webp';
import a92 from 'figma:asset/b279dde34844bf811593002f3c7a9cc64efd09f4.webp';
import a93 from 'figma:asset/b611fb7a41cfd7184ddb4f0b6c2291b82a180473.webp';
import a94 from 'figma:asset/b707207661364e701a223bac11e846c5d7451d6c.webp';
import a95 from 'figma:asset/b7ccff613803cc12fb0982f00b28c21d2e99b4c3.webp';
import a96 from 'figma:asset/baf09441eaec422eef72f951d09ce50d1e0cf702.webp';
import a97 from 'figma:asset/bc407c2a561416993c60bb74fbd2163f0984ffc6.webp';
import a98 from 'figma:asset/c304c5a140180875ee400ad12926e35368f74a41.webp';
import a99 from 'figma:asset/c5e02822aa53a05bfacebd326cbc09d041ca0b4d.webp';
import a100 from 'figma:asset/cd5d7ada40db3d957daea1ac3cff6db6d8e80c86.webp';
import a101 from 'figma:asset/d1b2c94414d2afe52ca117dcc2c5abc3119782e7.webp';
import a102 from 'figma:asset/d49ce2b4da6a0e33e564535e6cc619d30f5b5dcd.webp';
import a103 from 'figma:asset/d4d95224e7f5f73b3b2366dadafc6cc9315837ca.webp';
import a104 from 'figma:asset/d57e0cf4c5c508756bddc826ab9044e1fd9a743e.webp';
import a105 from 'figma:asset/d83342724cbc50b362e5ca9d8593f60f456abcd8.webp';
import a106 from 'figma:asset/e83edb8bb8ec5cb0b40c79e5ae7b8e1359546baf.webp';
import a107 from 'figma:asset/e880e8b1aee3f2d543d70198b331935027f8f808.webp';
import a108 from 'figma:asset/ef0d378cfbd2332dd42290ab0d7c96abcd9f00b0.webp';
import a109 from 'figma:asset/f232760bcf0145253c281f4b4f1f06048dce537f.webp';
import a110 from 'figma:asset/f76e05ff05fe1a25986acbf32ad034cd75c5f966.webp';
import a111 from 'figma:asset/f87a07df8827e23dba6492bb11aa7487235a03f1.webp';
import a112 from 'figma:asset/fd3705c67233eed8d5e4aaf424c71b24f8685dc1.webp';
import a113 from 'figma:asset/ff659488ddca67ce2d2ea51b9e8965e2d85d8a1e.webp';
import a114 from 'figma:asset/logo-skinny-65.webp';

export const imageDimensions: Record<string, [number, number]> = {
  [a0]: [1280, 1707],
  [a1]: [656, 1000],
  [a2]: [953, 1287],
  [a3]: [959, 1290],
  [a4]: [1052, 1322],
  [a5]: [910, 808],
  [a6]: [1213, 922],
  [a7]: [1024, 768],
  [a8]: [1611, 646],
  [a9]: [1384, 876],
  [a10]: [1438, 814],
  [a11]: [1562, 1080],
  [a12]: [1761, 1089],
  [a13]: [1884, 1110],
  [a14]: [1144, 756],
  [a15]: [1191, 834],
  [a16]: [2000, 1500],
  [a17]: [1561, 682],
  [a18]: [1550, 620],
  [a19]: [1790, 1346],
  [a20]: [1792, 930],
  [a21]: [1992, 1290],
  [a22]: [1682, 1198],
  [a23]: [2000, 1096],
  [a24]: [2000, 1096],
  [a25]: [2000, 1096],
  [a26]: [2000, 1096],
  [a27]: [189, 233],
  [a28]: [188, 247],
  [a29]: [225, 298],
  [a30]: [224, 298],
  [a31]: [199, 243],
  [a32]: [468, 196],
  [a33]: [184, 245],
  [a34]: [159, 211],
  [a35]: [510, 476],
  [a36]: [524, 460],
  [a37]: [588, 576],
  [a38]: [400, 399],
  [a39]: [268, 468],
  [a40]: [1500, 2000],
  [a41]: [990, 949],
  [a42]: [900, 1600],
  [a43]: [1086, 1018],
  [a44]: [1500, 2000],
  [a45]: [416, 454],
  [a46]: [534, 517],
  [a47]: [532, 392],
  [a48]: [1290, 1461],
  [a49]: [1125, 2000],
  [a50]: [610, 536],
  [a51]: [462, 522],
  [a52]: [1086, 470],
  [a53]: [2000, 1400],
  [a54]: [2000, 1334],
  [a55]: [496, 562],
  [a56]: [1290, 1595],
  [a57]: [495, 455],
  [a58]: [2000, 1960],
  [a59]: [635, 570],
  [a60]: [1030, 846],
  [a61]: [546, 404],
  [a62]: [940, 1190],
  [a63]: [972, 566],
  [a64]: [352, 440],
  [a65]: [851, 856],
  [a66]: [1099, 1137],
  [a67]: [1500, 2000],
  [a68]: [553, 430],
  [a69]: [578, 466],
  [a70]: [554, 670],
  [a71]: [898, 866],
  [a72]: [904, 1204],
  [a73]: [522, 415],
  [a74]: [344, 436],
  [a75]: [1500, 2000],
  [a76]: [690, 517],
  [a77]: [706, 712],
  [a78]: [1160, 2000],
  [a79]: [899, 783],
  [a80]: [942, 874],
  [a81]: [1314, 1030],
  [a82]: [1500, 2000],
  [a83]: [1268, 1022],
  [a84]: [605, 602],
  [a85]: [1500, 2000],
  [a86]: [1100, 462],
  [a87]: [852, 626],
  [a88]: [1290, 1625],
  [a89]: [1290, 1662],
  [a90]: [446, 418],
  [a91]: [1089, 2000],
  [a92]: [662, 415],
  [a93]: [2000, 1500],
  [a94]: [532, 424],
  [a95]: [882, 1238],
  [a96]: [845, 880],
  [a97]: [274, 446],
  [a98]: [1060, 931],
  [a99]: [820, 956],
  [a100]: [484, 322],
  [a101]: [541, 394],
  [a102]: [292, 536],
  [a103]: [1290, 1166],
  [a104]: [512, 464],
  [a105]: [630, 560],
  [a106]: [440, 440],
  [a107]: [978, 948],
  [a108]: [918, 1226],
  [a109]: [705, 352],
  [a110]: [779, 625],
  [a111]: [1200, 1600],
  [a112]: [2000, 1406],
  [a113]: [1536, 1024],
  [a114]: [351, 300],
};

/** width/height attrs for an image URL, or {} if it is not a bundled asset. */
export function dimsFor(src: string): { width?: number; height?: number } {
  const d = imageDimensions[src];
  return d ? { width: d[0], height: d[1] } : {};
}
